services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: eduplatform-db
    environment:
      POSTGRES_DB: eduplatform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eduplatform-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: eduplatform-api
    environment:
      DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/eduplatform"
      JWT_SECRET: "seu-jwt-secret-super-seguro"
      JWT_EXPIRES_IN: "7d"
      PORT: 3001
      FRONTEND_URL: "http://localhost:3000"
    ports:
      - "3001:3001"
      - "5556:5555" # Changed mapping for Prisma Studio to avoid port conflict
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - eduplatform-network
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  # Frontend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduplatform-web
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001/api"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - eduplatform-network
    command: npm run dev

  # pgAdmin - Interface gráfica para PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: eduplatform-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eduplatform.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - eduplatform-network

volumes:
  postgres_data:

networks:
  eduplatform-network:
    driver: bridge
